project:
  type: website
  output-dir: docs

website:
  title: "Zubin.research()"
  favicon: favicon.ico
  
  navbar: false          # we're using sidebar, not top nav
  
  sidebar:
    style: "docked"
    background: "dark"
    contents:
          - text: "~ home"
            href: index.qmd
          - text: "~ research"
            href: research/index.qmd
          - text: "~ blog"
            href: blog/index.qmd
          - text: "~ media_bank"
            href: media.qmd

format:
  html:
    theme: [darkly, custom.scss]
    toc: false
    code-fold: true
    code-tools: true
    lightbox: true